services:
  frontend:
    ports:
      - "3091:80"  # 测试端口
  backend:
    volumes:
      - vta-files-dev:/app/files        # 测试音频文件，与生产隔离
      - vta-db-dev:/app/database        # 测试数据库，与生产隔离

volumes:
  vta-files-dev:
  vta-db-dev:
